var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_mappers_1_1_helpdesk =
[
    [ "ISupportTicketMapper", "d3/dc8/interface_fenix_alliance_1_1_a_b_m_1_1_models_1_1_mappers_1_1_helpdesk_1_1_i_support_ticket_mapper.html", "d3/dc8/interface_fenix_alliance_1_1_a_b_m_1_1_models_1_1_mappers_1_1_helpdesk_1_1_i_support_ticket_mapper" ],
    [ "SupportTicketMapper", "d1/dff/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_mappers_1_1_helpdesk_1_1_support_ticket_mapper.html", "d1/dff/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_mappers_1_1_helpdesk_1_1_support_ticket_mapper" ]
];