var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_licensing_1_1_attributes =
[
    [ "LicenseAttribute", "d4/d3b/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_licensing_1_1_attributes_1_1_license_attribute.html", "d4/d3b/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_licensing_1_1_attributes_1_1_license_attribute" ]
];