var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_helpdesk_1_1_support_tickets_1_1_support_ticket_types =
[
    [ "SupportTicketType", "d0/d82/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_helpdesk_1_1_support_tickets_1_1_support_ticket_types_1_1_support_ticket_type.html", "d0/d82/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_helpdesk_1_1_support_tickets_1_1_support_ticket_types_1_1_support_ticket_type" ]
];