var class_nu_get_gallery_1_1_services_1_1_support_request_service_facts =
[
    [ "TheDeleteSupportRequestsAsync", "d8/d84/class_nu_get_gallery_1_1_services_1_1_support_request_service_facts_1_1_the_delete_support_requests_async.html", "d8/d84/class_nu_get_gallery_1_1_services_1_1_support_request_service_facts_1_1_the_delete_support_requests_async" ]
];