var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_services_1_1_service_fulfillment_preferences =
[
    [ "ServiceFulfillmentPreference", "d9/db1/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_services_1_1_service_fulfillment_preferences_1_1_service_fulfillment_preference.html", "d9/db1/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_services_1_1_service_fulfillment_preferences_1_1_service_fulfillment_preference" ]
];