var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_marketing_1_1_campaigns =
[
    [ "MarketingCampaign", "db/d62/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_marketing_1_1_campaigns_1_1_marketing_campaign.html", "db/d62/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_marketing_1_1_campaigns_1_1_marketing_campaign" ]
];