var namespace_nu_get_gallery_1_1_authentication_1_1_providers_1_1_microsoft_account =
[
    [ "MicrosoftAccountAuthenticator", "db/d6f/class_nu_get_gallery_1_1_authentication_1_1_providers_1_1_microsoft_account_1_1_microsoft_account_authenticator.html", "db/d6f/class_nu_get_gallery_1_1_authentication_1_1_providers_1_1_microsoft_account_1_1_microsoft_account_authenticator" ],
    [ "MicrosoftAccountAuthenticatorConfiguration", "d3/da3/class_nu_get_gallery_1_1_authentication_1_1_providers_1_1_microsoft_account_1_1_microsoft_account_authenticator_configuration.html", "d3/da3/class_nu_get_gallery_1_1_authentication_1_1_providers_1_1_microsoft_account_1_1_microsoft_account_authenticator_configuration" ]
];