var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_workforce_1_1_leaves_1_1_leave_applications =
[
    [ "LeaveApplication", "d8/d3f/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_workforce_1_1_leaves_1_1_leave_applications_1_1_leave_application.html", "d8/d3f/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_workforce_1_1_leaves_1_1_leave_applications_1_1_leave_application" ]
];