var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_accounting_1_1_taxes_1_1_tax_authorities =
[
    [ "FiscalAuthority", "d3/dab/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_accounting_1_1_taxes_1_1_tax_authorities_1_1_fiscal_authority.html", "d3/dab/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_accounting_1_1_taxes_1_1_tax_authorities_1_1_fiscal_authority" ]
];