var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_businesses_1_1_business_structure =
[
    [ "BusinessPositions", "d5/d06/namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_businesses_1_1_business_structure_1_1_business_positions.html", "d5/d06/namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_businesses_1_1_business_structure_1_1_business_positions" ]
];