var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_projects_1_1_opportunities =
[
    [ "ProjectOpportuinity", "db/dc8/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_projects_1_1_opportunities_1_1_project_opportuinity.html", "db/dc8/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_projects_1_1_opportunities_1_1_project_opportuinity" ]
];