var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_content_1_1_web_portals =
[
    [ "WebPortalBusinessDomainRecord", "d5/d69/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_content_1_1_web_portals_1_1_web_portal_business_domain_record.html", "d5/d69/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_content_1_1_web_portals_1_1_web_portal_business_domain_record" ],
    [ "WebPortal", "d2/de4/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_content_1_1_web_portals_1_1_web_portal.html", "d2/de4/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_content_1_1_web_portals_1_1_web_portal" ]
];