[book]
authors = ["Daniel Lozano"]
multilingual = false
language = "en"

src = "."
title = "Alliance Business Suite Documentation"
description = "The Ultimate Business Development Platform"

[build]
build-dir = "/book"
create-missing = false

[output.html.search]
enable = true

[output.html.fold]
enable = true
level = 0