var namespace_fenix_alliance_1_1_areas_1_1_legal_1_1_controllers_1_1_policies =
[
    [ "PoliciesController", "db/daf/class_fenix_alliance_1_1_areas_1_1_legal_1_1_controllers_1_1_policies_1_1_policies_controller.html", "db/daf/class_fenix_alliance_1_1_areas_1_1_legal_1_1_controllers_1_1_policies_1_1_policies_controller" ]
];