var namespace_fenix_alliance_1_1_a_c_l_1_1_configuration_1_1_types_1_1_i_c_x_1_1_recomendations =
[
    [ "RecommendationOptions", "d3/d0e/class_fenix_alliance_1_1_a_c_l_1_1_configuration_1_1_types_1_1_i_c_x_1_1_recomendations_1_1_recommendation_options.html", "d3/d0e/class_fenix_alliance_1_1_a_c_l_1_1_configuration_1_1_types_1_1_i_c_x_1_1_recomendations_1_1_recommendation_options" ]
];