var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_logistics_1_1_warehousing_1_1_item_packing_slips =
[
    [ "ItemPackingSlip", "dc/dbf/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_logistics_1_1_warehousing_1_1_item_packing_slips_1_1_item_packing_slip.html", "dc/dbf/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_logistics_1_1_warehousing_1_1_item_packing_slips_1_1_item_packing_slip" ],
    [ "ItemPackingSlipEntry", "d1/d39/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_logistics_1_1_warehousing_1_1_item_packing_slips_1_1_item_packing_slip_entry.html", "d1/d39/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_logistics_1_1_warehousing_1_1_item_packing_slips_1_1_item_packing_slip_entry" ]
];