var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_accounting_1_1_shares_1_1_share_transfer_reasons =
[
    [ "ShareTransferReason", "d6/da8/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_accounting_1_1_shares_1_1_share_transfer_reasons_1_1_share_transfer_reason.html", "d6/da8/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_accounting_1_1_shares_1_1_share_transfer_reasons_1_1_share_transfer_reason" ]
];