var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_accounting_1_1_accounts_1_1_accounting_entries =
[
    [ "AccountingEntry", "d4/d7e/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_accounting_1_1_accounts_1_1_accounting_entries_1_1_accounting_entry.html", "d4/d7e/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_accounting_1_1_accounts_1_1_accounting_entries_1_1_accounting_entry" ]
];