var namespace_fenix_alliance_1_1_a_b_p_1_1_a_p_i_1_1_graph_ql_1_1_core_1_1_middleware =
[
    [ "GraphQLHttpMiddlewareWithLogs", "da/d0e/class_fenix_alliance_1_1_a_b_p_1_1_a_p_i_1_1_graph_ql_1_1_core_1_1_middleware_1_1_graph_q_l_http_middleware_with_logs.html", "da/d0e/class_fenix_alliance_1_1_a_b_p_1_1_a_p_i_1_1_graph_ql_1_1_core_1_1_middleware_1_1_graph_q_l_http_middleware_with_logs" ],
    [ "GraphQlMiddleware", "da/d12/class_fenix_alliance_1_1_a_b_p_1_1_a_p_i_1_1_graph_ql_1_1_core_1_1_middleware_1_1_graph_ql_middleware.html", "da/d12/class_fenix_alliance_1_1_a_b_p_1_1_a_p_i_1_1_graph_ql_1_1_core_1_1_middleware_1_1_graph_ql_middleware" ]
];