var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_sales_1_1_attachment =
[
    [ "SalesLiteratureAttachment", "d5/d85/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_sales_1_1_attachment_1_1_sales_literature_attachment.html", "d5/d85/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_sales_1_1_attachment_1_1_sales_literature_attachment" ]
];