var namespace_fenix_alliance_1_1_a_b_s_1_1_portal_1_1_editor_1_1_controllers =
[
    [ "BuilderController", "d9/dc8/class_fenix_alliance_1_1_a_b_s_1_1_portal_1_1_editor_1_1_controllers_1_1_builder_controller.html", "d9/dc8/class_fenix_alliance_1_1_a_b_s_1_1_portal_1_1_editor_1_1_controllers_1_1_builder_controller" ]
];