var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_global_1_1_integrations_1_1_service_connectors_1_1_shippo =
[
    [ "ShippoConnector", "d1/d5f/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_global_1_1_integrations_1_1_service_connectors_1_1_shippo_1_1_shippo_connector.html", null ]
];