var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_workforce_1_1_leaves_1_1_leave_interval_requests =
[
    [ "LeaveIntervalRequest", "df/dd4/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_workforce_1_1_leaves_1_1_leave_interval_requests_1_1_leave_interval_request.html", "df/dd4/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_workforce_1_1_leaves_1_1_leave_interval_requests_1_1_leave_interval_request" ]
];