var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_projects_1_1_assignments =
[
    [ "ProjectTaskAssignments", "de/df5/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_projects_1_1_assignments_1_1_project_task_assignments.html", "de/df5/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_projects_1_1_assignments_1_1_project_task_assignments" ]
];