var namespace_fenix_alliance_1_1_a_b_p_1_1_bot_engine_1_1_core_1_1_auth_1_1_token_request =
[
    [ "BotTokenRequestPayload", "d5/da3/class_fenix_alliance_1_1_a_b_p_1_1_bot_engine_1_1_core_1_1_auth_1_1_token_request_1_1_bot_token_request_payload.html", "d5/da3/class_fenix_alliance_1_1_a_b_p_1_1_bot_engine_1_1_core_1_1_auth_1_1_token_request_1_1_bot_token_request_payload" ],
    [ "BotTokenRequestUser", "dd/dbc/class_fenix_alliance_1_1_a_b_p_1_1_bot_engine_1_1_core_1_1_auth_1_1_token_request_1_1_bot_token_request_user.html", "dd/dbc/class_fenix_alliance_1_1_a_b_p_1_1_bot_engine_1_1_core_1_1_auth_1_1_token_request_1_1_bot_token_request_user" ]
];