var class_nu_get_gallery_1_1_package_file_service_facts =
[
    [ "TheCreateDownloadPackageActionResultMethod", "d7/d4b/class_nu_get_gallery_1_1_package_file_service_facts_1_1_the_create_download_package_action_result_method.html", "d7/d4b/class_nu_get_gallery_1_1_package_file_service_facts_1_1_the_create_download_package_action_result_method" ],
    [ "TheDeletePackageFileMethod", "d2/deb/class_nu_get_gallery_1_1_package_file_service_facts_1_1_the_delete_package_file_method.html", "d2/deb/class_nu_get_gallery_1_1_package_file_service_facts_1_1_the_delete_package_file_method" ],
    [ "TheDeleteReadMeMdFileAsync", "d1/df2/class_nu_get_gallery_1_1_package_file_service_facts_1_1_the_delete_read_me_md_file_async.html", "d1/df2/class_nu_get_gallery_1_1_package_file_service_facts_1_1_the_delete_read_me_md_file_async" ],
    [ "TheDownloadReadMeMdFileAsyncMethod", "dd/da7/class_nu_get_gallery_1_1_package_file_service_facts_1_1_the_download_read_me_md_file_async_method.html", "dd/da7/class_nu_get_gallery_1_1_package_file_service_facts_1_1_the_download_read_me_md_file_async_method" ],
    [ "TheSaveReadMeMdFileAsyncMethod", "db/dc5/class_nu_get_gallery_1_1_package_file_service_facts_1_1_the_save_read_me_md_file_async_method.html", "db/dc5/class_nu_get_gallery_1_1_package_file_service_facts_1_1_the_save_read_me_md_file_async_method" ]
];