var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_assets_1_1_asset_categories =
[
    [ "AssetCategory", "de/da4/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_assets_1_1_asset_categories_1_1_asset_category.html", "de/da4/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_assets_1_1_asset_categories_1_1_asset_category" ]
];