var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_education_1_1_courses_1_1_certificates =
[
    [ "CourseCompletionCertificate", "d0/de6/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_education_1_1_courses_1_1_certificates_1_1_course_completion_certificate.html", "d0/de6/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_education_1_1_courses_1_1_certificates_1_1_course_completion_certificate" ],
    [ "CourseCompletionCertificateTemplate", "d7/dfd/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_education_1_1_courses_1_1_certificates_1_1_course_completion_certificate_template.html", "d7/dfd/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_education_1_1_courses_1_1_certificates_1_1_course_completion_certificate_template" ]
];