var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_security_1_1_business_security_logs =
[
    [ "BusinessSecurityLog", "d1/de2/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_security_1_1_business_security_logs_1_1_business_security_log.html", "d1/de2/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_security_1_1_business_security_logs_1_1_business_security_log" ]
];