var namespace_fenix_alliance_1_1_a_p_s_1_1_core_1_1_identity_server_1_1_device =
[
    [ "DeviceAuthorizationInputModel", "dc/d9f/class_fenix_alliance_1_1_a_p_s_1_1_core_1_1_identity_server_1_1_device_1_1_device_authorization_input_model.html", "dc/d9f/class_fenix_alliance_1_1_a_p_s_1_1_core_1_1_identity_server_1_1_device_1_1_device_authorization_input_model" ],
    [ "DeviceAuthorizationViewModel", "df/da7/class_fenix_alliance_1_1_a_p_s_1_1_core_1_1_identity_server_1_1_device_1_1_device_authorization_view_model.html", "df/da7/class_fenix_alliance_1_1_a_p_s_1_1_core_1_1_identity_server_1_1_device_1_1_device_authorization_view_model" ],
    [ "DeviceController", "db/d0a/class_fenix_alliance_1_1_a_p_s_1_1_core_1_1_identity_server_1_1_device_1_1_device_controller.html", "db/d0a/class_fenix_alliance_1_1_a_p_s_1_1_core_1_1_identity_server_1_1_device_1_1_device_controller" ]
];