var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_cognitive_1_1_cognitive_agents =
[
    [ "CognitiveAgent", "d6/d53/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_cognitive_1_1_cognitive_agents_1_1_cognitive_agent.html", "d6/d53/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_cognitive_1_1_cognitive_agents_1_1_cognitive_agent" ],
    [ "CognitiveAgentConversation", "d0/d7c/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_cognitive_1_1_cognitive_agents_1_1_cognitive_agent_conversation.html", "d0/d7c/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_cognitive_1_1_cognitive_agents_1_1_cognitive_agent_conversation" ]
];