var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_assets_1_1_asset_maintenance_roles =
[
    [ "AssetMaintenanceRole", "d2/d5f/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_assets_1_1_asset_maintenance_roles_1_1_asset_maintenance_role.html", "d2/d5f/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_assets_1_1_asset_maintenance_roles_1_1_asset_maintenance_role" ]
];