var class_nu_get_gallery_1_1_queries_1_1_autocomplete_database_package_versions_query_facts_1_1_constructor =
[
    [ "InvalidArgumentsThrowsArgumentNullException", "db/dfb/class_nu_get_gallery_1_1_queries_1_1_autocomplete_database_package_versions_query_facts_1_1_constructor.html#a7bf509dc764ff212f7655ec8ce4a0ae7", null ]
];