var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_tenants_1_1_business_structure_1_1_business_units =
[
    [ "BusinessUnitRecords", "dc/d8d/namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_tenants_1_1_business_structure_1_1_business_units_1_1_business_unit_records.html", "dc/d8d/namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_tenants_1_1_business_structure_1_1_business_units_1_1_business_unit_records" ],
    [ "BusinessUnit", "db/d99/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_tenants_1_1_business_structure_1_1_business_units_1_1_business_unit.html", "db/d99/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_tenants_1_1_business_structure_1_1_business_units_1_1_business_unit" ]
];