var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_logistics_1_1_shipping_1_1_shipping_regions =
[
    [ "ShippingRegion", "d3/db9/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_logistics_1_1_shipping_1_1_shipping_regions_1_1_shipping_region.html", "d3/db9/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_logistics_1_1_shipping_1_1_shipping_regions_1_1_shipping_region" ],
    [ "ShippingRegionCountryRecord", "d2/df4/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_logistics_1_1_shipping_1_1_shipping_regions_1_1_shipping_region_country_record.html", "d2/df4/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_logistics_1_1_shipping_1_1_shipping_regions_1_1_shipping_region_country_record" ],
    [ "ShippingRegionZoneRecord", "d5/d34/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_logistics_1_1_shipping_1_1_shipping_regions_1_1_shipping_region_zone_record.html", "d5/d34/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_logistics_1_1_shipping_1_1_shipping_regions_1_1_shipping_region_zone_record" ]
];