var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_blockchains_1_1_n_f_ts =
[
    [ "NonFungibleToken", "da/d18/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_blockchains_1_1_n_f_ts_1_1_non_fungible_token.html", "da/d18/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_blockchains_1_1_n_f_ts_1_1_non_fungible_token" ],
    [ "NonFungibleTokenOwnership", "d3/df6/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_blockchains_1_1_n_f_ts_1_1_non_fungible_token_ownership.html", "d3/df6/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_blockchains_1_1_n_f_ts_1_1_non_fungible_token_ownership" ]
];