var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_global_1_1_startups_1_1_startup_program_registrations =
[
    [ "StartupProgramRecord", "d8/d52/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_global_1_1_startups_1_1_startup_program_registrations_1_1_startup_program_record.html", "d8/d52/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_global_1_1_startups_1_1_startup_program_registrations_1_1_startup_program_record" ]
];