var class_nu_get_gallery_1_1_asynchronous_package_validation_initiator_facts_1_1_the_start_symbols_package_validation_async_method =
[
    [ "AddsEntityKeyAsAppropriate", "da/dfb/class_nu_get_gallery_1_1_asynchronous_package_validation_initiator_facts_1_1_the_start_symbols_package_validation_async_method.html#a27981f2322bc0d8a902c3e878ba38efc", null ],
    [ "FailsWhenTheGalleryIsInReadOnlyMode", "da/dfb/class_nu_get_gallery_1_1_asynchronous_package_validation_initiator_facts_1_1_the_start_symbols_package_validation_async_method.html#ab896bfd058ff4d224acb1cbd7b6c85f1", null ],
    [ "ReturnsCorrectPackageStatusInBlockingMode", "da/dfb/class_nu_get_gallery_1_1_asynchronous_package_validation_initiator_facts_1_1_the_start_symbols_package_validation_async_method.html#ab0561b22613f7a5c349db19310fda01d", null ],
    [ "ReturnsCorrectPackageStatusInNonBlockingMode", "da/dfb/class_nu_get_gallery_1_1_asynchronous_package_validation_initiator_facts_1_1_the_start_symbols_package_validation_async_method.html#a6ab3a73a5d16b03bb0b15c57d1c6accb", null ],
    [ "UsesADifferentValidationTrackingIdEachTime", "da/dfb/class_nu_get_gallery_1_1_asynchronous_package_validation_initiator_facts_1_1_the_start_symbols_package_validation_async_method.html#a1ee25dfc2f234c9d84d8192dd019df2d", null ],
    [ "UsesProvidedPackageIdAndVersion", "da/dfb/class_nu_get_gallery_1_1_asynchronous_package_validation_initiator_facts_1_1_the_start_symbols_package_validation_async_method.html#a90436a117175dabdaa7eb3a2fd7cfed4", null ]
];