var namespace_fenix_alliance_1_1_areas_1_1_admin_1_1_controllers_1_1_businesses =
[
    [ "IndustriesController", "da/d15/class_fenix_alliance_1_1_areas_1_1_admin_1_1_controllers_1_1_businesses_1_1_industries_controller.html", "da/d15/class_fenix_alliance_1_1_areas_1_1_admin_1_1_controllers_1_1_businesses_1_1_industries_controller" ],
    [ "SegmentsController", "d9/d3f/class_fenix_alliance_1_1_areas_1_1_admin_1_1_controllers_1_1_businesses_1_1_segments_controller.html", "d9/d3f/class_fenix_alliance_1_1_areas_1_1_admin_1_1_controllers_1_1_businesses_1_1_segments_controller" ]
];