var namespace_fenix_alliance_1_1_a_b_p_1_1_bot_engine_1_1_core_1_1_extensions =
[
    [ "BotAdapterWithErrorHandler", "da/d65/class_fenix_alliance_1_1_a_b_p_1_1_bot_engine_1_1_core_1_1_extensions_1_1_bot_adapter_with_error_handler.html", "da/d65/class_fenix_alliance_1_1_a_b_p_1_1_bot_engine_1_1_core_1_1_extensions_1_1_bot_adapter_with_error_handler" ]
];