var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_projects_1_1_task_buckets =
[
    [ "ProjectTaskBucket", "dd/d2e/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_projects_1_1_task_buckets_1_1_project_task_bucket.html", "dd/d2e/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_projects_1_1_task_buckets_1_1_project_task_bucket" ],
    [ "ProjectTaskBucketRecord", "d9/dcc/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_projects_1_1_task_buckets_1_1_project_task_bucket_record.html", "d9/dcc/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_projects_1_1_task_buckets_1_1_project_task_bucket_record" ]
];