var class_nu_get_gallery_1_1_controllers_1_1_features_controller_facts_1_1_features_controller_facts_base =
[
    [ "SetupGetModel", "de/da9/class_nu_get_gallery_1_1_controllers_1_1_features_controller_facts_1_1_features_controller_facts_base.html#ae36dcca1df2b9c8489d95ff8d9ac689c", null ]
];