var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_workforce_1_1_leaves_1_1_leave_blocked_intervals =
[
    [ "LeaveBlockedInterval", "d1/d86/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_workforce_1_1_leaves_1_1_leave_blocked_intervals_1_1_leave_blocked_interval.html", "d1/d86/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_workforce_1_1_leaves_1_1_leave_blocked_intervals_1_1_leave_blocked_interval" ]
];