var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_workforce_1_1_jobs_1_1_job_applications =
[
    [ "JobOfferApplication", "db/df5/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_workforce_1_1_jobs_1_1_job_applications_1_1_job_offer_application.html", "db/df5/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_workforce_1_1_jobs_1_1_job_applications_1_1_job_offer_application" ]
];