var class_nu_get_gallery_1_1_functional_tests_1_1_xunit_extensions_1_1_default_security_policies_enforced_fact_attribute =
[
    [ "DefaultSecurityPoliciesEnforcedFactAttribute", "db/d51/class_nu_get_gallery_1_1_functional_tests_1_1_xunit_extensions_1_1_default_security_policies_enforced_fact_attribute.html#a95b6eb527b51e71280d8ff534f1221ec", null ]
];