var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_quality_1_1_quality_work_flows =
[
    [ "QualityWorkflow", "db/d6e/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_quality_1_1_quality_work_flows_1_1_quality_workflow.html", "db/d6e/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_quality_1_1_quality_work_flows_1_1_quality_workflow" ]
];