var class_nu_get_gallery_1_1_security_1_1_require_organization_tenant_policy_facts_1_1_the_evaluate_method =
[
    [ "WhenMatchingTargetCredential_ReturnsSuccess", "dd/d2c/class_nu_get_gallery_1_1_security_1_1_require_organization_tenant_policy_facts_1_1_the_evaluate_method.html#aaf615aa2ceb6a301ce26a00b86c93701", null ],
    [ "WhenNoMatchingTargetCredential_ReturnsError", "dd/d2c/class_nu_get_gallery_1_1_security_1_1_require_organization_tenant_policy_facts_1_1_the_evaluate_method.html#af1d5dfa6b9fc8117bb5ccb6cda8ad9f1", null ]
];