var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_cloud_1_1_manager_1_1_cloud_service_providers =
[
    [ "CloudServiceProvider", "df/d06/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_cloud_1_1_manager_1_1_cloud_service_providers_1_1_cloud_service_provider.html", "df/d06/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_cloud_1_1_manager_1_1_cloud_service_providers_1_1_cloud_service_provider" ]
];