var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_helpdesk_1_1_support_tickets =
[
    [ "SupportTicketPriorities", "d7/d4e/namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_helpdesk_1_1_support_tickets_1_1_support_ticket_priorities.html", "d7/d4e/namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_helpdesk_1_1_support_tickets_1_1_support_ticket_priorities" ],
    [ "SupportTicketTypes", "d7/db8/namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_helpdesk_1_1_support_tickets_1_1_support_ticket_types.html", "d7/db8/namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_helpdesk_1_1_support_tickets_1_1_support_ticket_types" ],
    [ "SupportTicket", "d9/de4/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_helpdesk_1_1_support_tickets_1_1_support_ticket.html", "d9/de4/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_helpdesk_1_1_support_tickets_1_1_support_ticket" ]
];