var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_marketing_1_1_email_templates =
[
    [ "EmailTemplate", "d3/da1/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_marketing_1_1_email_templates_1_1_email_template.html", "d3/da1/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_marketing_1_1_email_templates_1_1_email_template" ]
];