var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_tenants_1_1_business_profile_invites =
[
    [ "BusinessProfileInvitation", "d0/d66/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_tenants_1_1_business_profile_invites_1_1_business_profile_invitation.html", "d0/d66/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_tenants_1_1_business_profile_invites_1_1_business_profile_invitation" ]
];