var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_global_1_1_integrations_1_1_payment_gateways_1_1_nequi =
[
    [ "NequiConnector", "d6/d5f/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_global_1_1_integrations_1_1_payment_gateways_1_1_nequi_1_1_nequi_connector.html", null ]
];