var class_nu_get_gallery_1_1_package_service_facts =
[
    [ "TheAddPackageOwnerMethod", "d6/d5e/class_nu_get_gallery_1_1_package_service_facts_1_1_the_add_package_owner_method.html", "d6/d5e/class_nu_get_gallery_1_1_package_service_facts_1_1_the_add_package_owner_method" ],
    [ "TheCreatePackageMethod", "d4/dc9/class_nu_get_gallery_1_1_package_service_facts_1_1_the_create_package_method.html", "d4/dc9/class_nu_get_gallery_1_1_package_service_facts_1_1_the_create_package_method" ],
    [ "TheEnrichPackageFromNuGetPackageMethod", "dc/d80/class_nu_get_gallery_1_1_package_service_facts_1_1_the_enrich_package_from_nu_get_package_method.html", "dc/d80/class_nu_get_gallery_1_1_package_service_facts_1_1_the_enrich_package_from_nu_get_package_method" ],
    [ "TheEnsureValidMethod", "de/dda/class_nu_get_gallery_1_1_package_service_facts_1_1_the_ensure_valid_method.html", "de/dda/class_nu_get_gallery_1_1_package_service_facts_1_1_the_ensure_valid_method" ],
    [ "TheFilterExactPackageMethod", "db/d84/class_nu_get_gallery_1_1_package_service_facts_1_1_the_filter_exact_package_method.html", "db/d84/class_nu_get_gallery_1_1_package_service_facts_1_1_the_filter_exact_package_method" ],
    [ "TheFilterLatestPackageMethod", "db/dac/class_nu_get_gallery_1_1_package_service_facts_1_1_the_filter_latest_package_method.html", "db/dac/class_nu_get_gallery_1_1_package_service_facts_1_1_the_filter_latest_package_method" ],
    [ "TheFindPackageByIdAndVersionMethod", "dd/d11/class_nu_get_gallery_1_1_package_service_facts_1_1_the_find_package_by_id_and_version_method.html", "dd/d11/class_nu_get_gallery_1_1_package_service_facts_1_1_the_find_package_by_id_and_version_method" ],
    [ "TheFindPackageBySuffixMethod", "d0/d32/class_nu_get_gallery_1_1_package_service_facts_1_1_the_find_package_by_suffix_method.html", "d0/d32/class_nu_get_gallery_1_1_package_service_facts_1_1_the_find_package_by_suffix_method" ],
    [ "TheFindPackagesByAnyMatchingOwnerMethod", "de/d30/class_nu_get_gallery_1_1_package_service_facts_1_1_the_find_packages_by_any_matching_owner_method.html", "de/d30/class_nu_get_gallery_1_1_package_service_facts_1_1_the_find_packages_by_any_matching_owner_method" ],
    [ "TheFindPackagesByOwnerMethod", "d8/dcf/class_nu_get_gallery_1_1_package_service_facts_1_1_the_find_packages_by_owner_method.html", "d8/dcf/class_nu_get_gallery_1_1_package_service_facts_1_1_the_find_packages_by_owner_method" ],
    [ "TheFindPackagesByOwnersMethodsBase", "d1/dcc/class_nu_get_gallery_1_1_package_service_facts_1_1_the_find_packages_by_owners_methods_base.html", "d1/dcc/class_nu_get_gallery_1_1_package_service_facts_1_1_the_find_packages_by_owners_methods_base" ],
    [ "TheGetPackageDependentsMethod", "d3/df3/class_nu_get_gallery_1_1_package_service_facts_1_1_the_get_package_dependents_method.html", "d3/df3/class_nu_get_gallery_1_1_package_service_facts_1_1_the_get_package_dependents_method" ],
    [ "ThePublishPackageMethod", "d8/d7a/class_nu_get_gallery_1_1_package_service_facts_1_1_the_publish_package_method.html", "d8/d7a/class_nu_get_gallery_1_1_package_service_facts_1_1_the_publish_package_method" ],
    [ "TheRemovePackageOwnerMethod", "d5/dec/class_nu_get_gallery_1_1_package_service_facts_1_1_the_remove_package_owner_method.html", "d5/dec/class_nu_get_gallery_1_1_package_service_facts_1_1_the_remove_package_owner_method" ],
    [ "TheSetLicenseReportVisibilityMethod", "d9/db6/class_nu_get_gallery_1_1_package_service_facts_1_1_the_set_license_report_visibility_method.html", "d9/db6/class_nu_get_gallery_1_1_package_service_facts_1_1_the_set_license_report_visibility_method" ],
    [ "TheSetRequiredSignerAsyncMethodOneParameter", "da/d13/class_nu_get_gallery_1_1_package_service_facts_1_1_the_set_required_signer_async_method_one_parameter.html", "da/d13/class_nu_get_gallery_1_1_package_service_facts_1_1_the_set_required_signer_async_method_one_parameter" ],
    [ "TheSetRequiredSignerAsyncMethodTwoParameters", "df/dc4/class_nu_get_gallery_1_1_package_service_facts_1_1_the_set_required_signer_async_method_two_parameters.html", "df/dc4/class_nu_get_gallery_1_1_package_service_facts_1_1_the_set_required_signer_async_method_two_parameters" ],
    [ "TheWillOrphanPackageIfOwnerRemovedMethod", "de/df5/class_nu_get_gallery_1_1_package_service_facts_1_1_the_will_orphan_package_if_owner_removed_method.html", "de/df5/class_nu_get_gallery_1_1_package_service_facts_1_1_the_will_orphan_package_if_owner_removed_method" ]
];