var namespace_fenix_alliance_1_1_a_b_m_1_1_data_1_1_access_1_1_clients =
[
    [ "BlobStorageDataAccessClient", "d1/d82/class_fenix_alliance_1_1_a_b_m_1_1_data_1_1_access_1_1_clients_1_1_blob_storage_data_access_client.html", "d1/d82/class_fenix_alliance_1_1_a_b_m_1_1_data_1_1_access_1_1_clients_1_1_blob_storage_data_access_client" ],
    [ "ContextDataAccessClient", "db/dc6/class_fenix_alliance_1_1_a_b_m_1_1_data_1_1_access_1_1_clients_1_1_context_data_access_client.html", "db/dc6/class_fenix_alliance_1_1_a_b_m_1_1_data_1_1_access_1_1_clients_1_1_context_data_access_client" ],
    [ "HolderDataAccessClient", "d6/d20/class_fenix_alliance_1_1_a_b_m_1_1_data_1_1_access_1_1_clients_1_1_holder_data_access_client.html", "d6/d20/class_fenix_alliance_1_1_a_b_m_1_1_data_1_1_access_1_1_clients_1_1_holder_data_access_client" ],
    [ "SocialDataAccessClient", "db/db4/class_fenix_alliance_1_1_a_b_m_1_1_data_1_1_access_1_1_clients_1_1_social_data_access_client.html", "db/db4/class_fenix_alliance_1_1_a_b_m_1_1_data_1_1_access_1_1_clients_1_1_social_data_access_client" ],
    [ "StockDataAccessClient", "dc/dfc/class_fenix_alliance_1_1_a_b_m_1_1_data_1_1_access_1_1_clients_1_1_stock_data_access_client.html", "dc/dfc/class_fenix_alliance_1_1_a_b_m_1_1_data_1_1_access_1_1_clients_1_1_stock_data_access_client" ],
    [ "StorageDataAccessClient", "d7/ddd/class_fenix_alliance_1_1_a_b_m_1_1_data_1_1_access_1_1_clients_1_1_storage_data_access_client.html", "d7/ddd/class_fenix_alliance_1_1_a_b_m_1_1_data_1_1_access_1_1_clients_1_1_storage_data_access_client" ],
    [ "TenantDataAccessClient", "de/d3d/class_fenix_alliance_1_1_a_b_m_1_1_data_1_1_access_1_1_clients_1_1_tenant_data_access_client.html", "de/d3d/class_fenix_alliance_1_1_a_b_m_1_1_data_1_1_access_1_1_clients_1_1_tenant_data_access_client" ]
];