var namespace_fenix_alliance_1_1_a_b_p_1_1_hub_1_1_middleware =
[
    [ "WorkflowsAuthorizationMiddleware", "df/d70/class_fenix_alliance_1_1_a_b_p_1_1_hub_1_1_middleware_1_1_workflows_authorization_middleware.html", "df/d70/class_fenix_alliance_1_1_a_b_p_1_1_hub_1_1_middleware_1_1_workflows_authorization_middleware" ]
];