var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_projects_1_1_project_tasks =
[
    [ "ProjectTask", "dd/dca/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_projects_1_1_project_tasks_1_1_project_task.html", "dd/dca/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_projects_1_1_project_tasks_1_1_project_task" ],
    [ "ProjectTaskRelationship", "dc/d36/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_projects_1_1_project_tasks_1_1_project_task_relationship.html", "dc/d36/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_projects_1_1_project_tasks_1_1_project_task_relationship" ]
];