var _principal_extensions_facts_8cs =
[
    [ "PrincipalExtensionsFacts", "dd/db6/class_nu_get_gallery_1_1_extensions_1_1_principal_extensions_facts.html", [
      [ "TheGetAuthenticationTypeMethod", "d4/d3b/class_nu_get_gallery_1_1_extensions_1_1_principal_extensions_facts_1_1_the_get_authentication_type_method.html", "d4/d3b/class_nu_get_gallery_1_1_extensions_1_1_principal_extensions_facts_1_1_the_get_authentication_type_method" ],
      [ "TheGetClaimOrDefaultMethod", "d9/d44/class_nu_get_gallery_1_1_extensions_1_1_principal_extensions_facts_1_1_the_get_claim_or_default_method.html", "d9/d44/class_nu_get_gallery_1_1_extensions_1_1_principal_extensions_facts_1_1_the_get_claim_or_default_method" ],
      [ "TheGetScopesFromClaimMethod", "dd/da0/class_nu_get_gallery_1_1_extensions_1_1_principal_extensions_facts_1_1_the_get_scopes_from_claim_method.html", "dd/da0/class_nu_get_gallery_1_1_extensions_1_1_principal_extensions_facts_1_1_the_get_scopes_from_claim_method" ],
      [ "TheHasExplicitScopeActionMethod", "dd/d97/class_nu_get_gallery_1_1_extensions_1_1_principal_extensions_facts_1_1_the_has_explicit_scope_action_method.html", "dd/d97/class_nu_get_gallery_1_1_extensions_1_1_principal_extensions_facts_1_1_the_has_explicit_scope_action_method" ],
      [ "TheHasScopeThatAllowsActionsMethod", "dc/df3/class_nu_get_gallery_1_1_extensions_1_1_principal_extensions_facts_1_1_the_has_scope_that_allows_actions_method.html", "dc/df3/class_nu_get_gallery_1_1_extensions_1_1_principal_extensions_facts_1_1_the_has_scope_that_allows_actions_method" ],
      [ "TheIsAdministratorMethod", "d5/dc5/class_nu_get_gallery_1_1_extensions_1_1_principal_extensions_facts_1_1_the_is_administrator_method.html", "d5/dc5/class_nu_get_gallery_1_1_extensions_1_1_principal_extensions_facts_1_1_the_is_administrator_method" ],
      [ "TheIsScopedAuthenticationMethod", "d3/db3/class_nu_get_gallery_1_1_extensions_1_1_principal_extensions_facts_1_1_the_is_scoped_authentication_method.html", "d3/db3/class_nu_get_gallery_1_1_extensions_1_1_principal_extensions_facts_1_1_the_is_scoped_authentication_method" ]
    ] ],
    [ "TheGetClaimOrDefaultMethod", "d9/d44/class_nu_get_gallery_1_1_extensions_1_1_principal_extensions_facts_1_1_the_get_claim_or_default_method.html", "d9/d44/class_nu_get_gallery_1_1_extensions_1_1_principal_extensions_facts_1_1_the_get_claim_or_default_method" ],
    [ "TheGetAuthenticationTypeMethod", "d4/d3b/class_nu_get_gallery_1_1_extensions_1_1_principal_extensions_facts_1_1_the_get_authentication_type_method.html", "d4/d3b/class_nu_get_gallery_1_1_extensions_1_1_principal_extensions_facts_1_1_the_get_authentication_type_method" ],
    [ "TheGetScopesFromClaimMethod", "dd/da0/class_nu_get_gallery_1_1_extensions_1_1_principal_extensions_facts_1_1_the_get_scopes_from_claim_method.html", "dd/da0/class_nu_get_gallery_1_1_extensions_1_1_principal_extensions_facts_1_1_the_get_scopes_from_claim_method" ],
    [ "TheIsAdministratorMethod", "d5/dc5/class_nu_get_gallery_1_1_extensions_1_1_principal_extensions_facts_1_1_the_is_administrator_method.html", "d5/dc5/class_nu_get_gallery_1_1_extensions_1_1_principal_extensions_facts_1_1_the_is_administrator_method" ],
    [ "TheIsScopedAuthenticationMethod", "d3/db3/class_nu_get_gallery_1_1_extensions_1_1_principal_extensions_facts_1_1_the_is_scoped_authentication_method.html", "d3/db3/class_nu_get_gallery_1_1_extensions_1_1_principal_extensions_facts_1_1_the_is_scoped_authentication_method" ],
    [ "TheHasExplicitScopeActionMethod", "dd/d97/class_nu_get_gallery_1_1_extensions_1_1_principal_extensions_facts_1_1_the_has_explicit_scope_action_method.html", "dd/d97/class_nu_get_gallery_1_1_extensions_1_1_principal_extensions_facts_1_1_the_has_explicit_scope_action_method" ],
    [ "TheHasScopeThatAllowsActionsMethod", "dc/df3/class_nu_get_gallery_1_1_extensions_1_1_principal_extensions_facts_1_1_the_has_scope_that_allows_actions_method.html", "dc/df3/class_nu_get_gallery_1_1_extensions_1_1_principal_extensions_facts_1_1_the_has_scope_that_allows_actions_method" ],
    [ "AuthenticationTypes", "da/dfd/_principal_extensions_facts_8cs.html#a87c5fb35623fbaddc8040c3ac442786f", null ]
];