var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_services_1_1_service_case_subjects =
[
    [ "ServiceCaseType", "df/db7/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_services_1_1_service_case_subjects_1_1_service_case_type.html", "df/db7/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_services_1_1_service_case_subjects_1_1_service_case_type" ]
];