var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_projects_1_1_price_lists =
[
    [ "ProjectPriceListRecord", "de/d92/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_projects_1_1_price_lists_1_1_project_price_list_record.html", "de/d92/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_projects_1_1_price_lists_1_1_project_price_list_record" ]
];