var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_marketing_1_1_post_buckets =
[
    [ "SocialPostBucket", "de/d13/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_marketing_1_1_post_buckets_1_1_social_post_bucket.html", "de/d13/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_marketing_1_1_post_buckets_1_1_social_post_bucket" ]
];