var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_social_1_1_conversations_1_1_scopes =
[
    [ "SupportTicketConversation", "d5/d9c/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_social_1_1_conversations_1_1_scopes_1_1_support_ticket_conversation.html", "d5/d9c/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_social_1_1_conversations_1_1_scopes_1_1_support_ticket_conversation" ]
];