var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_procurement_1_1_supplier_score_cards =
[
    [ "SupplierScorecard", "d4/d80/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_procurement_1_1_supplier_score_cards_1_1_supplier_scorecard.html", "d4/d80/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_procurement_1_1_supplier_score_cards_1_1_supplier_scorecard" ]
];