var namespace_nu_get_gallery_1_1_security =
[
    [ "AutomaticallyOverwriteRequiredSignerPolicy", "d0/d61/class_nu_get_gallery_1_1_security_1_1_automatically_overwrite_required_signer_policy.html", "d0/d61/class_nu_get_gallery_1_1_security_1_1_automatically_overwrite_required_signer_policy" ],
    [ "ControlRequiredSignerPolicy", "db/dae/class_nu_get_gallery_1_1_security_1_1_control_required_signer_policy.html", "db/dae/class_nu_get_gallery_1_1_security_1_1_control_required_signer_policy" ],
    [ "DefaultSubscription", "dd/dbd/class_nu_get_gallery_1_1_security_1_1_default_subscription.html", "dd/dbd/class_nu_get_gallery_1_1_security_1_1_default_subscription" ],
    [ "ISecurityPolicyService", "dc/d94/interface_nu_get_gallery_1_1_security_1_1_i_security_policy_service.html", "dc/d94/interface_nu_get_gallery_1_1_security_1_1_i_security_policy_service" ],
    [ "IUserSecurityPolicySubscription", "db/d8c/interface_nu_get_gallery_1_1_security_1_1_i_user_security_policy_subscription.html", "db/d8c/interface_nu_get_gallery_1_1_security_1_1_i_user_security_policy_subscription" ],
    [ "MicrosoftTeamSubscription", "d6/dcd/class_nu_get_gallery_1_1_security_1_1_microsoft_team_subscription.html", "d6/dcd/class_nu_get_gallery_1_1_security_1_1_microsoft_team_subscription" ],
    [ "PackageSecurityPolicyEvaluationContext", "dd/d07/class_nu_get_gallery_1_1_security_1_1_package_security_policy_evaluation_context.html", "dd/d07/class_nu_get_gallery_1_1_security_1_1_package_security_policy_evaluation_context" ],
    [ "PackageSecurityPolicyHandler", "d3/d1e/class_nu_get_gallery_1_1_security_1_1_package_security_policy_handler.html", "d3/d1e/class_nu_get_gallery_1_1_security_1_1_package_security_policy_handler" ],
    [ "RequiredSignerPolicy", "d5/de4/class_nu_get_gallery_1_1_security_1_1_required_signer_policy.html", "d5/de4/class_nu_get_gallery_1_1_security_1_1_required_signer_policy" ],
    [ "RequireMinProtocolVersionForPushPolicy", "d3/d38/class_nu_get_gallery_1_1_security_1_1_require_min_protocol_version_for_push_policy.html", "d3/d38/class_nu_get_gallery_1_1_security_1_1_require_min_protocol_version_for_push_policy" ],
    [ "RequireOrganizationTenantPolicy", "dd/d3d/class_nu_get_gallery_1_1_security_1_1_require_organization_tenant_policy.html", "dd/d3d/class_nu_get_gallery_1_1_security_1_1_require_organization_tenant_policy" ],
    [ "RequirePackageMetadataCompliancePolicy", "d3/d18/class_nu_get_gallery_1_1_security_1_1_require_package_metadata_compliance_policy.html", "d3/d18/class_nu_get_gallery_1_1_security_1_1_require_package_metadata_compliance_policy" ],
    [ "RequirePackageMetadataState", "d4/dec/class_nu_get_gallery_1_1_security_1_1_require_package_metadata_state.html", "d4/dec/class_nu_get_gallery_1_1_security_1_1_require_package_metadata_state" ],
    [ "RequirePackageVerifyScopePolicy", "d0/d8d/class_nu_get_gallery_1_1_security_1_1_require_package_verify_scope_policy.html", "d0/d8d/class_nu_get_gallery_1_1_security_1_1_require_package_verify_scope_policy" ],
    [ "SecurityPolicyHandler", "d8/d4f/class_nu_get_gallery_1_1_security_1_1_security_policy_handler.html", "d8/d4f/class_nu_get_gallery_1_1_security_1_1_security_policy_handler" ],
    [ "SecurityPolicyResult", "d7/d11/class_nu_get_gallery_1_1_security_1_1_security_policy_result.html", "d7/d11/class_nu_get_gallery_1_1_security_1_1_security_policy_result" ],
    [ "SecurityPolicyService", "d6/d1f/class_nu_get_gallery_1_1_security_1_1_security_policy_service.html", "d6/d1f/class_nu_get_gallery_1_1_security_1_1_security_policy_service" ],
    [ "UserSecurityPolicyEvaluationContext", "d7/d0e/class_nu_get_gallery_1_1_security_1_1_user_security_policy_evaluation_context.html", "d7/d0e/class_nu_get_gallery_1_1_security_1_1_user_security_policy_evaluation_context" ],
    [ "UserSecurityPolicyHandler", "d0/d73/class_nu_get_gallery_1_1_security_1_1_user_security_policy_handler.html", "d0/d73/class_nu_get_gallery_1_1_security_1_1_user_security_policy_handler" ],
    [ "UserSecurityPolicySubscriptionContext", "d6/da3/class_nu_get_gallery_1_1_security_1_1_user_security_policy_subscription_context.html", "d6/da3/class_nu_get_gallery_1_1_security_1_1_user_security_policy_subscription_context" ],
    [ "AutomaticallyOverwriteRequiredSignerPolicyFacts", "d8/db4/class_nu_get_gallery_1_1_security_1_1_automatically_overwrite_required_signer_policy_facts.html", "d8/db4/class_nu_get_gallery_1_1_security_1_1_automatically_overwrite_required_signer_policy_facts" ],
    [ "ControlRequiredSignerPolicyFacts", "da/d1a/class_nu_get_gallery_1_1_security_1_1_control_required_signer_policy_facts.html", "da/d1a/class_nu_get_gallery_1_1_security_1_1_control_required_signer_policy_facts" ],
    [ "DefaultSubscriptionFacts", "dd/dc2/class_nu_get_gallery_1_1_security_1_1_default_subscription_facts.html", "dd/dc2/class_nu_get_gallery_1_1_security_1_1_default_subscription_facts" ],
    [ "MicrosoftTeamSubscriptionFacts", "d4/d55/class_nu_get_gallery_1_1_security_1_1_microsoft_team_subscription_facts.html", "d4/d55/class_nu_get_gallery_1_1_security_1_1_microsoft_team_subscription_facts" ],
    [ "RequireMinProtocolVersionForPushPolicyFacts", "da/dc5/class_nu_get_gallery_1_1_security_1_1_require_min_protocol_version_for_push_policy_facts.html", "da/dc5/class_nu_get_gallery_1_1_security_1_1_require_min_protocol_version_for_push_policy_facts" ],
    [ "RequireOrganizationTenantPolicyFacts", "db/d1c/class_nu_get_gallery_1_1_security_1_1_require_organization_tenant_policy_facts.html", "db/d1c/class_nu_get_gallery_1_1_security_1_1_require_organization_tenant_policy_facts" ],
    [ "RequirePackageMetadataCompliancePolicyFacts", "d5/dca/class_nu_get_gallery_1_1_security_1_1_require_package_metadata_compliance_policy_facts.html", "d5/dca/class_nu_get_gallery_1_1_security_1_1_require_package_metadata_compliance_policy_facts" ],
    [ "RequirePackageVerifyScopePolicyFacts", "dc/d7d/class_nu_get_gallery_1_1_security_1_1_require_package_verify_scope_policy_facts.html", "dc/d7d/class_nu_get_gallery_1_1_security_1_1_require_package_verify_scope_policy_facts" ],
    [ "SecurityPolicyServiceFacts", "d4/d96/class_nu_get_gallery_1_1_security_1_1_security_policy_service_facts.html", "d4/d96/class_nu_get_gallery_1_1_security_1_1_security_policy_service_facts" ],
    [ "TestSecurityPolicyService", "d5/d26/class_nu_get_gallery_1_1_security_1_1_test_security_policy_service.html", "d5/d26/class_nu_get_gallery_1_1_security_1_1_test_security_policy_service" ],
    [ "TestUserSecurityPolicyData", "df/db7/class_nu_get_gallery_1_1_security_1_1_test_user_security_policy_data.html", "df/db7/class_nu_get_gallery_1_1_security_1_1_test_user_security_policy_data" ],
    [ "SecurityPolicyAction", "dc/d9c/namespace_nu_get_gallery_1_1_security.html#afe2a12beed889bd73502091c27d1399a", [
      [ "PackagePush", "dc/d9c/namespace_nu_get_gallery_1_1_security.html#afe2a12beed889bd73502091c27d1399aaf3f4d0fa463f5db24986b87778b269d0", null ],
      [ "PackageVerify", "dc/d9c/namespace_nu_get_gallery_1_1_security.html#afe2a12beed889bd73502091c27d1399aac5b578fdf92daefbd0cc50ef16506c98", null ],
      [ "ManagePackageOwners", "dc/d9c/namespace_nu_get_gallery_1_1_security.html#afe2a12beed889bd73502091c27d1399aaf1622d2bdf7de7ac78a3e21e3531ae8d", null ],
      [ "JoinOrganization", "dc/d9c/namespace_nu_get_gallery_1_1_security.html#afe2a12beed889bd73502091c27d1399aa6e36d4efb505cfbfbe9b3aa58cccdee9", null ],
      [ "AutomaticallyOverwriteRequiredSigner", "dc/d9c/namespace_nu_get_gallery_1_1_security.html#afe2a12beed889bd73502091c27d1399aaa7ba61c980c62ff013f9fd22e49379a5", null ],
      [ "ControlRequiredSigner", "dc/d9c/namespace_nu_get_gallery_1_1_security.html#afe2a12beed889bd73502091c27d1399aa5c5e804e95340a37f41d7ee276c029f2", null ]
    ] ]
];