var class_nu_get_gallery_1_1_controllers_1_1_features_controller_facts =
[
    [ "FeatureBase", "d1/d5c/class_nu_get_gallery_1_1_controllers_1_1_features_controller_facts_1_1_feature_base.html", "d1/d5c/class_nu_get_gallery_1_1_controllers_1_1_features_controller_facts_1_1_feature_base" ],
    [ "FeaturesControllerFactsBase", "de/da9/class_nu_get_gallery_1_1_controllers_1_1_features_controller_facts_1_1_features_controller_facts_base.html", "de/da9/class_nu_get_gallery_1_1_controllers_1_1_features_controller_facts_1_1_features_controller_facts_base" ],
    [ "FlightBase", "df/d98/class_nu_get_gallery_1_1_controllers_1_1_features_controller_facts_1_1_flight_base.html", "df/d98/class_nu_get_gallery_1_1_controllers_1_1_features_controller_facts_1_1_flight_base" ],
    [ "ModifyMethodBase", "d1/dfc/class_nu_get_gallery_1_1_controllers_1_1_features_controller_facts_1_1_modify_method_base.html", "d1/dfc/class_nu_get_gallery_1_1_controllers_1_1_features_controller_facts_1_1_modify_method_base" ],
    [ "TheAddFeatureMethod", "d6/d3b/class_nu_get_gallery_1_1_controllers_1_1_features_controller_facts_1_1_the_add_feature_method.html", "d6/d3b/class_nu_get_gallery_1_1_controllers_1_1_features_controller_facts_1_1_the_add_feature_method" ],
    [ "TheAddFlightMethod", "dd/dd5/class_nu_get_gallery_1_1_controllers_1_1_features_controller_facts_1_1_the_add_flight_method.html", "dd/dd5/class_nu_get_gallery_1_1_controllers_1_1_features_controller_facts_1_1_the_add_flight_method" ],
    [ "TheDeleteFeatureMethod", "d9/d6d/class_nu_get_gallery_1_1_controllers_1_1_features_controller_facts_1_1_the_delete_feature_method.html", "d9/d6d/class_nu_get_gallery_1_1_controllers_1_1_features_controller_facts_1_1_the_delete_feature_method" ],
    [ "TheDeleteFlightMethod", "db/daa/class_nu_get_gallery_1_1_controllers_1_1_features_controller_facts_1_1_the_delete_flight_method.html", "db/daa/class_nu_get_gallery_1_1_controllers_1_1_features_controller_facts_1_1_the_delete_flight_method" ],
    [ "TheEditFeatureMethod", "d6/d63/class_nu_get_gallery_1_1_controllers_1_1_features_controller_facts_1_1_the_edit_feature_method.html", "d6/d63/class_nu_get_gallery_1_1_controllers_1_1_features_controller_facts_1_1_the_edit_feature_method" ],
    [ "TheEditFlightMethod", "d3/da0/class_nu_get_gallery_1_1_controllers_1_1_features_controller_facts_1_1_the_edit_flight_method.html", "d3/da0/class_nu_get_gallery_1_1_controllers_1_1_features_controller_facts_1_1_the_edit_flight_method" ],
    [ "TheIndexMethod", "d1/dd4/class_nu_get_gallery_1_1_controllers_1_1_features_controller_facts_1_1_the_index_method.html", "d1/dd4/class_nu_get_gallery_1_1_controllers_1_1_features_controller_facts_1_1_the_index_method" ]
];