var namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_helpdesk_1_1_knowledge_articles =
[
    [ "KnowledgeArticleCategories", "d1/de0/namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_helpdesk_1_1_knowledge_articles_1_1_knowledge_article_categories.html", "d1/de0/namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_helpdesk_1_1_knowledge_articles_1_1_knowledge_article_categories" ],
    [ "KnowledgeArticleTemplates", "df/d2d/namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_helpdesk_1_1_knowledge_articles_1_1_knowledge_article_templates.html", "df/d2d/namespace_fenix_alliance_1_1_a_b_m_1_1_models_1_1_helpdesk_1_1_knowledge_articles_1_1_knowledge_article_templates" ],
    [ "KnowledgeArticle", "d5/dbc/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_helpdesk_1_1_knowledge_articles_1_1_knowledge_article.html", "d5/dbc/class_fenix_alliance_1_1_a_b_m_1_1_models_1_1_helpdesk_1_1_knowledge_articles_1_1_knowledge_article" ]
];